# Generated by Django 5.2.1 on 2025-05-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(blank=True, default=1, upload_to='products/')),
                ('stock', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories', unique=None)),
            ],
        ),
    ]
