# Generated by Django 5.2.1 on 2025-05-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('product', '0004_remove_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
    ]
