# Generated by Django 5.2.1 on 2025-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
